apiVersion: v2
name: github-runnerset
description: Github Actions RunnerSet
type: application
version: 1.0.0
dependencies:
  - name: gha-runner-scale-set
    version: 0.12.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
